### ISSUE TITLE
Pico switches lose connectivity

### ISSUE THREAD

**Issue by mikesalz** [smockle/homebridge-lutron-caseta#12]
Using Homebridge version 0.4.50... The plugin works perfectly for days or weeks.  Then, for seemingly no reason, all of my Pico switches stop triggering actions.  A Homebridge restart fixes the issue.  I don't see any errors or messages in the logs.

**Comment by mikesalz** [comment]
Follow-up: I think I know what the issue is.  It seems that if there is a power flicker or outage and the Caseta bridge temporarily loses power, Homebridge does not automatically reconnect to it.  Is there a way to have the plugin periodically check the connection and reconnect if the connection has been broken?

**Comment by mikesalz** [comment]
I have noticed a couple of updates to the plugin since I posted this.  Just curious - Did these correct the issue?

**Comment by smockle** [comment]
@mikesalz Thanks for following up! I have not added any new code to check connection status. The recent updates have been triggered automatically when this plugin’s dependencies are updated, in order to incorporate security and bug fixes.

**Comment by smockle** [comment]
I do not use Lutron Caséta switches or remotes anymore, and I’m unlikely to undertake any new development on this plugin in the near future.

I’ve considered [deprecating it in the `npm` registry](https://docs.npmjs.com/cli/deprecate) and [archiving this repository](https://help.github.com/en/articles/archiving-a-github-repository). I haven’t done so (yet) because that would stop the automated testing & updates that occur when this plugin’s dependencies are updated.

My reason for preserving the automated dependency updates is to help this plugin’s remaining users stay up-to-date with security and bug fixes. If that update strategy is actually _confusing_ this plugin’s users, though, then I can turn it off. Do you have a preference @mikesalz?

**Comment by mikesalz** [comment]
Hey @smockle!  Thanks for getting back to me.  I don't know how many people use this plugin, but I'll be honest: It has totally changed the way I use HomeKit! I have several Pico remotes that use the plugin, with automations as simple as turning on groups of Hue lights, and as complicated as locking/unlocking doors and setting the home alarm (that remote is what I give to house sitters when we are out of town, rather than a physical key). 

I very much appreciate all of the hard work you put into this plugin, and would hate for it to go away.  But I understand you have moved on and don't want to be forced to continue to support a plugin that you yourself no longer even use.

To answer your question... I would say leave it turned on. But in the description, add a short blurb explaining exactly what you told me - That it is no longer being updated but its dependencies are.

**Comment by smockle** [comment]
> To answer your question... I would say leave it turned on. But in the description, add a short blurb explaining exactly what you told me - That it is no longer being updated but its dependencies are.

👍 Sounds good, thanks @mikesalz! Added this message via #14.
